# Generated by Django 5.1.5 on 2025-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='bloghome/user-50.png', upload_to='UsersAccount/images'),
        ),
    ]
