# Generated by Django 5.1.5 on 2025-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAccount', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='UserAccount/images/default.png', upload_to='UsersAccount/images'),
        ),
    ]
