# Generated by Django 5.1.5 on 2025-04-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAccount', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_Profile',
            new_name='user',
        ),
    ]
