# Generated by Django 5.1.5 on 2025-05-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAccount', '0009_rename_user_profile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Desc',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_edited_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
