# Generated by Django 5.1.5 on 2025-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0002_gamingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='image',
            field=models.ImageField(default='', upload_to='Gaming/images'),
        ),
    ]
