# Generated by Django 5.1.5 on 2025-04-10 12:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0003_gaming_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
