# Generated by Django 5.1.5 on 2025-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0004_alter_gaming_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming',
            name='category',
        ),
    ]
