# Generated by Django 5.1.5 on 2025-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0005_remove_gaming_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming',
            name='price',
        ),
    ]
