# Generated by Django 5.1.5 on 2025-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0006_remove_gaming_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
