# Generated by Django 5.1.5 on 2025-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0009_remove_gaming_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
