# Generated by Django 5.1.5 on 2025-04-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0011_alter_gaming_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming',
            name='author',
        ),
    ]
