# Generated by Django 5.1.5 on 2025-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='image',
            field=models.ImageField(default='', upload_to='Software/images'),
        ),
    ]
