# Generated by Django 5.1.5 on 2025-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0003_alter_software_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='category',
        ),
    ]
