# Generated by Django 5.1.5 on 2025-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0006_alter_software_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='post_type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
