# Generated by Django 5.1.5 on 2025-04-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0007_software_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='product_name',
        ),
    ]
