# Generated by Django 5.1.5 on 2025-04-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0010_alter_software_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='author',
        ),
    ]
