# Generated by Django 5.1.5 on 2025-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('Ele_id_sno', models.AutoField(primary_key=True, serialize=False)),
                ('product_header', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=3000)),
                ('author', models.CharField(default='', max_length=13)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
