# Generated by Django 5.1.5 on 2025-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0005_alter_electronics_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='category',
        ),
    ]
