# Generated by Django 5.1.5 on 2025-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0006_remove_electronics_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='price',
        ),
    ]
