# Generated by Django 5.1.5 on 2025-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0007_remove_electronics_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
