# Generated by Django 5.1.5 on 2025-04-27 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0011_alter_electronics_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
