# Generated by Django 5.1.5 on 2025-04-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0012_alter_electronics_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='author',
        ),
    ]
